config/routes.rb
WMBadminton::Application.routes.draw do
  devise_for :admins
  root 'static_pages#home'

  resources :players

  #match '/signup',      to: 'players#new',              via: 'get'
  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'
  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  #match '/tournament',  to: 'static_pages#tournament',  via: 'get'
  #match '/rules',       to: 'static_pages#rules',       via: 'get'
  match '/gallery',     to: 'static_pages#gallery',     via: 'get'

  #match '/teamlist',    to: 'static_pages#md',          via: 'get'
  #match '/md',          to: 'static_pages#md',          via: 'get'
  #match '/wd',          to: 'static_pages#wd',          via: 'get'
  #match '/xd',          to: 'static_pages#xd',          via: 'get'
  #match '/brackets',    to: 'static_pages#brackets',    via: 'get' 
  match '/results',     to: 'static_pages#results',     via: 'get' 

  # Sitemap stuff
  match '/sitemap.xml.gz' => 'sitemaps#show',           via: 'get'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  after_create :send_admin_mail
  def send_admin_mail
      AdminMailer.new_admin_waiting_for_approval(self).deliver
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  before_save { self.email = email.downcase }


  self.per_page = 10

  validates :name, presence: true, length: { maximum: 30 }

  validates :signature, presence: true
  validates :address_street, presence: true
  validates :phone, presence: true
  validates :address_city_state, presence: true
  validates :address_zip, presence: true
  validates :fees, presence: true
  validates :skill, presence: true
  validates :gender, presence: true

  # Required to make boolean presence validation
  validates_inclusion_of :md, :in => [true, false]
  validates_inclusion_of :wd, :in => [true, false]
  validates_inclusion_of :xd, :in => [true, false]


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player= Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if admin_signed_in? 
      if @player.update_attributes(player_params)
        flash[:success] = "Profile updated"
        redirect_to @player
      end
    else
      render 'edit'
    end
  end

  def new
    @player = Player.new
  end

  def index
    @q = Player.search(params[:q])
    @players = @q.result.paginate(page: params[:page]).order('id ASC')
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      flash[:success] = "Thanks for signing up for the tournament!" 
      redirect_to @player
    else
      render 'new'
    end
  end

  def destroy
    Player.find(params[:id]).destroy
    flash[:success] = "Player destroyed." 
    redirect_to players_url
  end

  def edit
    @player = Player.find(params[:id])
  end

  private
    def player_params
      params.require(:player).permit(:name, 
                                   :gender,
:email, 
:address_street, 
:address_city_state, 
:address_zip, 
:phone,
:club, 
:fees, 
:signature,
:md, 
:wd, 
:xd,
:md_partner, 
:wd_partner,
:xd_partner,
:skill)
    end
end

app/controllers/sitemap_controller.rb
class SitemapsController < ApplicationController
  def show
    # Redirect to CloudFront and S3
    redirect_to "http://d1ifn4fgg0ycb6.cloudfront.net/sitemaps/sitemap.xml.gz"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end
  
  def about
  end

  def contact
  end

  def tournament
  end

  def rules
  end

  def gallery
    @images = Dir.glob("app/assets/images/gallery/*.{gif,jpg,png}")
  end

  def teamlist
  end

  def md
  end

  def wd
  end

  def xd
  end

  def results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "wmbadminton"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/players_helper.rb
module PlayersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given player.
  def gravatar_for(player)
    gravatar_id = Digest::MD5::hexdigest(player.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: player.name, class: "gravatar")
  end

  def gravatar_for(player, options = { size: 150})
    gravatar_id = Digest::MD5::hexdigest(player.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: player.name, class: "gravatar")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44780208-1', 'wmbadminton.herokuapp.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_footer.html.erb
<div class="container"> 
<footer class="footer spacer">
  <small>
    webapp for william and mary badminton club by sameer dhar.
  </small>
</footer>
</div> 

app/views/layouts/_header.html.erb
<div class="container"> 
<nav class="navbar navbar-inverse" role="navigation" >
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "wmbadminton", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right" > 
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <li><%= link_to "Contact", contact_path %></li> 
        <li><%= link_to "Pictures", gallery_path %></li>
      </ul>
    </div>
  </div>
</nav>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="Description" 
      content="William and Mary Badminton Club's official website">
    <meta name="Keywords" 
      content="wm, badminton, wmbadminton, william and mary, william, mary, tournament, club">
  </head>
  <body>
    <%= render 'layouts/header' %> 
    <div class="container">

      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <div class="container">
        <%= yield %>
      </div>

    </div>

      <%= render 'layouts/footer' %>
      <%= render 'layouts/analytics' if Rails.env.production? %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/players/_player.html.erb
<li>
<div class="container">
  <div class="row"> 
    <div class="col-md-8 text-left"> 
      <%= link_to player.name, player %>
    </div>

    <div class="col-md-4 text-right"> 
      Paid: <%= player.paid %>
      <% if admin_signed_in? %>
        <%= link_to "delete", player, method: :delete,
                                      data: { confirm: "You sure?" }, class: "btn btn-xs btn-danger" %>
        <%= link_to "edit", edit_player_path(player), class: "btn btn-xs btn-info" %>
      <% end %>
    </div> 

  </div>
  <div class="row"> 
    <div class="col-md-8"> 
      <%= player.club %>
    </div> 
</div> 
  
</li>

app/views/players/edit.html.erb
<% provide(:title, "Edit player") %>
<h1>Update a player's profile</h1>

  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for(@player, html: {class: 'form-horizontal spacer' }) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.input :name %> 
      <%= f.input :gender, collection: 'Male,Female'.split(',') %>
      <%= f.input :email %>
      <%= f.input :address_street,      label: 'Street address'  %> 
      <%= f.input :address_city_state,  label: 'City, State' %> 
      <%= f.input :address_zip,         label: 'Zipcode' %> 
      <%= f.input :phone, as: :tel,     label: 'Phone Number' %> 
      <%= f.input :club %> 

      <%= f.input :skill, collection: 'A,B,C,D'.split(',') %> 


      <%= f.input :md_partner, label: 'MD Partner' %>
      <%= f.input :wd_partner, label: 'WD Partner' %>
      <%= f.input :xd_partner, label: 'XD Partner' %>

      <%= f.input :fees, :class => 'input-small'  %>

      <%= f.submit "Save changes", class: "btn btn-lg btn-primary" %>
    <% end %>

  </div>

app/views/shared/_error_messages.html.erb
<% if @player.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@player.errors.count, "error") %>.
    </div>
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

  <h1>About Us</h1>

<div class="row spacer"> 
  <div class="col-md-3"> 
    <h4> Practice Times: </h4> 
    <ul> 
      <li> Mondays and Thursdays, 9:15 to 11:00 pm</li> 
      <li> Saturdays, 2:30 to 4:30 pm </li> 
    </ul>
    <h4 class="spacer"> Location: Adair Hall</h4> 
  </div> 
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron center"> 
  <h1>William and Mary Badminton</h1>
</div> 

<div class="row">
  <div class="col-md-4"> 
    <h2>Tournament News</h2> 

    <ol> 
      <li>The tournament has concluded, thank you all for coming and making this a success!</li> 
      <li>Results can be viewed at 
      <%= link_to "this link", results_path,
        class: "btn btn-xs btn-primary" %>.</li>
    </ol>
  </div> 

  <div class="col-md-8 text-center"> 

    <img src= <%= asset_path('Badminton-6.jpg') %> alt="Group picture!", class="img-rounded" >

  </div> 
</div>

app/views/static_pages/md.html.erb
<h1>Current Teams</h1> 

<ul class="nav nav-tabs nav-justified">
  <li class="active"><%= link_to "Men's Doubles", md_path %></li>
    <li><%= link_to "Women's Doubles", wd_path %></li>
    <li><%= link_to "Mixed Doubles", xd_path %></li>
</ul>

<div class="col-md-8 col-md-offset-2"> 
  <h2 class="spacer">Men's Doubles</h2> 
  <table class="table table-hover spacer">
    <thead>
    <tr>
      <th></th> 
      <th>Partner 1</th> 
      <th>Partner 2</th>
      <th>Club</th> 
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>1</td>
      <td><%= link_to "Yudistira Virgus", player_path(5) %></td> 
      <td><%= link_to "Sameer Dhar", player_path(6) %> </td> 
      <td>William and Mary</td> 
    </tr>
    <tr>
      <td>2</td>
      <td><%= link_to "Shiwei Zhang", player_path(66) %></td> 
      <td><%= link_to "Karl Jacobson", player_path(56) %></td> 
      <td>William and Mary</td> 
    </tr> 

    <tr>
      <td>3</td>
      <td><%= link_to "Chunwang Gao", player_path(24) %></td> 
      <td><%= link_to "Weiping Yang", player_path(81) %></td> 
      <td>Richmond</td>
    </tr>

    <tr>
      <td>4</td>
      <td><%= link_to "Teck Ying Wong", player_path(76) %></td> 
      <td><%= link_to "Kin Weng Chee", player_path(77) %></td> 
      <td>Va Badminton</td>
    </tr>

    <tr>
      <td>5</td>
      <td><%= link_to "Donald Wunder", player_path(46) %></td> 
      <td><%= link_to "Matt De Francisco", player_path(50) %></td> 
      <td>Adelphi</td>
    </tr>

    <tr>
      <td>6</td>
      <td><%= link_to "Du Shen", player_path(57) %></td> 
      <td><%= link_to "Wei Xu", player_path(58) %></td>
      <td>William and Mary</td> 
    </tr> 

    <tr>
      <td>7</td>
      <td><%= link_to "Mike Crawshaw", player_path(40) %></td> 
      <td><%= link_to "Jun Yu", player_path(11) %></td>
      <td>Virginia Beach</td> 
    </tr> 

    <tr>
      <td>8</td>
      <td><%= link_to "Kevin Tran", player_path(7) %> </td> 
      <td><%= link_to "Daniel Marsden", player_path(14) %></td>
      <td>Virginia Beach</td> 
    </tr> 

    <tr>
      <td>9</td>
      <td><%= link_to "Xiaoping Yang", player_path(38) %></td> 
      <td><%= link_to "Gao Chen", player_path(68) %></td>
      <td>Virginia Beach</td> 
    </tr> 

    <tr>
      <td>10</td>
      <td><%= link_to "Truong Pham", player_path(67) %></td> 
      <td><%= link_to "Bill McMahon", player_path(65) %></td>
      <td>Duke</td> 
    </tr> 

    <tr>
      <td>11</td>
      <td><%= link_to "David Wang", player_path(29) %></td> 
      <td><%= link_to "Chris Flower", player_path(71) %></td>
      <td>Duke</td> 
    </tr> 

    <tr>
      <td>12</td>
      <td><%= link_to "Gary Zhang",   player_path(51) %></td> 
      <td><%= link_to "George Chang", player_path(34) %></td>
      <td>Duke</td> 
    </tr> 

    <tr>
      <td>13</td>
      <td><%= link_to "Pritak Patel", player_path(31) %></td> 
      <td><%= link_to "Stephen Kwok", player_path(52) %></td>
      <td>Duke</td> 
    </tr> 
    
    <tr>
      <td>14</td>
      <td><%= link_to "Henry Sun",  player_path(12) %></td> 
      <td><%= link_to "Desh Rajan", player_path(23) %></td> 
      <td>Virginia Beach</td> 
    </tr> 

    <tr>
      <td>15</td>
      <td><%= link_to "Rijo Reji", player_path(37) %></td> 
      <td><%= link_to "Satrio Gani", player_path(26) %></td>
      <td>RBC/WM</td> 
    </tr> 

    <tr>
      <td>16</td>
      <td><%= link_to "Brandon Hoe", player_path(19) %></td> 
      <td><%= link_to "Leon Grodski de Barrera", player_path(22) %></td> 
      <td>NCBC</td> 
    </tr> 
    </tbody>
  </table>
</div> 

<div class="col-md-8 col-md-offset-2">
  <h2 class="spacer">Wait List</h2>
  <table class="table table-hover spacer"> 
    <thead>
      <tr>
        <th></th>
        <th>Partner 1</th> 
        <th>Partner 2</th> 
        <th>Club</th> 
      </tr> 
    </thead>

    <tbody> 
      <tr>
        <td>1</td>
        <td><%= link_to "Nisaraj Dharmarajan", player_path(10) %></td> 
        <td><%= link_to "Xavier Konathappalli", player_path(13) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>2</td>
        <td><%= link_to "Wenson Ge", player_path(78) %></td> 
        <td><%= link_to "Mani Boopathy", player_path(75) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>3</td>
        <td><%= link_to "Don Lanka Ranasinghe", player_path(18) %></td>
        <td>Request</td>
        <td>Virginia Beach</td> 
      </tr>
    </tbody> 
  </table> 
</div>

app/views/static_pages/wd.html.erb
<h1>Current Teams</h1>

<ul class="nav nav-tabs nav-justified">
    <li><%= link_to "Men's Doubles", md_path %></li>
    <li class="active" ><%= link_to "Women's Doubles", wd_path %></li>
    <li><%= link_to "Mixed Doubles", xd_path %></li>
</ul>

<div class="col-md-8 col-md-offset-2">
  <table class="table table-hover spacer">
    <thead>
    <tr>
      <th></th> 
      <th>Partner 1</th> 
      <th>Partner 2</th>
      <th>Club</th> 
    </tr>
    </thead> 

    <tbody> 
    <tr>
      <td>1</td> 
      <td><%= link_to "Shan Li", player_path(59) %></td>
      <td><%= link_to "Jerri Nguyen", player_path(8) %></td>
      <td>William and Mary</td>
    </tr> 
    <tr>
      <td>2</td> 
      <td><%= link_to "Jenny Cheung", player_path(2) %> </td>
      <td><%= link_to "Sharon Ma", player_path(36) %></td>
      <td>VCU/RBC</td>
    </tr> 
    <tr>
      <td>3</td> 
      <td><%= link_to "Lingji Zhang", player_path(3) %> </td>
      <td><%= link_to "Pingping Fan", player_path(41) %></td>
      <td>Virginia Beach</td>
    </tr> 
    <tr>
      <td>4</td> 
      <td><%= link_to "Yao Zhao", player_path(49) %></td>
      <td><%= link_to "Alissa Montalbano", player_path(45) %></td>
      <td>Adelphi</td>
    </tr> 
    <tr>
      <td>5</td> 
      <td><%= link_to "Daylyn Wu", player_path(44) %></td>
      <td><%= link_to "Evelyn Rivera", player_path(42) %></td>
      <td>Adelphi</td>
    </tr> 

    <tr>
      <td>6</td> 
      <td><%= link_to "Maria Victoria Somers", player_path(9) %></td> 
      <td><%= link_to "Qingyan Zhu", player_path(39) %></td>
      <td>Virginia Beach</td> 
    </tr> 

    <tr>
      <td>7</td> 
      <td><%= link_to "Melissa Wu", player_path(69) %></td> 
      <td><%= link_to "Amy Zhao", player_path(33) %></td>
      <td>Duke</td> 
    </tr> 

    <tr>
      <td>8</td> 
      <td><%= link_to "Jeannie Yim", player_path(30) %></td> 
      <td><%= link_to "April Pun", player_path(61) %></td>
      <td>Duke</td> 
    </tr> 

      <tr>
        <td>9</td> 
        <td><%= link_to "Thi Pham", player_path(28) %></td> 
        <td><%= link_to "Judith Leng", player_path(54) %></td>
        <td>VCU/Duke</td> 
      </tr> 
      <tr>
        <td>10</td> 
        <td><%= link_to "Anusha Liyanage", player_path(16) %></td> 
        <td><%= link_to "Gayathri Shivaraj", player_path(17) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>11</td> 
        <td><%= link_to "Connie Wang", player_path(20) %> </td>
        <td><%= link_to "Yusun Wang", player_path(15) %></td>
        <td>JMU/VaB</td> 
      </tr> 
      <tr>
        <td>12</td> 
        <td><%= link_to "Lisa Lei", player_path(80) %> </td>
        <td><%= link_to "Anita Jiang", player_path(79) %></td>
        <td>WM</td> 
      </tr> 
    </tbody> 
  </table> 
</div> 

<div class="col-md-8 col-md-offset-2">
  <h2 class="spacer">Wait List</h2>
  <table class="table table-hover spacer"> 
    <thead>
      <tr>
        <th></th>
        <th>Partner 1</th> 
        <th>Partner 2</th> 
        <th>Club</th> 
      </tr> 
    </thead>

      <tr>
        <td>1</td> 
        <td><%= link_to "Hannah Nguyen", player_path(25) %> </td> 
        <td><%= link_to "Hoang Luu", player_path(63) %></td>
        <td></td> 
      </tr> 
    </tbody>
  </table> 
</div>

app/views/static_pages/xd.html.erb
<h1>Current Teams</h1>

<ul class="nav nav-tabs nav-justified">
    <li><%= link_to "Men's Doubles", md_path %></li>
    <li><%= link_to "Women's Doubles", wd_path %></li>
    <li class="active" ><%= link_to "Mixed Doubles", xd_path %></li>
</ul>

<div class="col-md-8 col-md-offset-2"> 
  <table class="table table-hover spacer"> 
    <thead> 
      <tr>
        <th></th> 
        <th>Partner 1</th> 
        <th>Partner 2</th> 
        <th>Club</th> 
      </tr> 
    </thead> 

    <tbody>
      <tr> 
        <td>1</td>
        <td><%= link_to "Yudistira Virgus", player_path(5) %></td> 
        <td><%= link_to "Jerri Nguyen", player_path(8) %></td> 
        <td>William and Mary</td> 
      </tr> 
      <tr> 
        <td>2</td>
        <td><%= link_to "Jin Su Hwang", player_path(53) %></td> 
        <td><%= link_to "Jenny Cheung", player_path(2) %> </td>
        <td>VCU</td> 
      </tr> 
      <tr> 
        <td>3</td>
        <td><%= link_to "Henry Sun", player_path(12) %></td> 
        <td><%= link_to "Lingji Zhang", player_path(3) %> </td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr> 
        <td>4</td>
        <td><%= link_to "Mani Boopathy", player_path(75) %></td> 
        <td><%= link_to "Gayathri Shivaraj", player_path(17) %></td> 
        <td>Virginia Beach</td> 
      </tr> 
      <tr> 
        <td>5</td>
        <td><%= link_to "Saqib Shah", player_path(74) %></td> 
        <td><%= link_to "Thi Pham", player_path(28) %></td> 
        <td>RBC/VCU</td> 
      </tr> 
      <tr> 
        <td>6</td>
        <td><%= link_to "Donald Wunder", player_path(46) %></td> 
        <td><%= link_to "Jenna Cavuto", player_path(43) %></td> 
        <td>Adelphi</td> 
      </tr> 
      <tr> 
        <td>7</td>
        <td><%= link_to "Matt De Francisco", player_path(50) %></td> 
        <td><%= link_to "Daylyn Wu", player_path(44) %></td> 
        <td>Adelphi</td> 
      </tr> 
      <tr>
        <td>8</td> 
        <td><%= link_to "Mike Crawshaw", player_path(40) %></td> 
        <td><%= link_to "Pingping Fan", player_path(41) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>9</td> 
        <td><%= link_to "Jun Yu", player_path(11) %></td> 
        <td><%= link_to "Yusun Wang", player_path(15) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>10</td> 
        <td><%= link_to "Kevin Tran", player_path(7) %></td> 
        <td><%= link_to "Maria Victoria Somers", player_path(9) %></td>
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>11</td> 
        <td><%= link_to "Xiaoping Yang", player_path(38) %></td>
        <td><%= link_to "Qingyan Zhu", player_path(39) %></td> 
        <td>Virginia Beach</td> 
      </tr> 
      <tr>
        <td>12</td> 
        <td><%= link_to "Chris Flower", player_path(71) %></td> 
        <td><%= link_to "Melissa Wu", player_path(69) %></td>
        <td>Duke</td> 
      </tr> 
      <tr>
        <td>13</td> 
        <td><%= link_to "David Wang", player_path(29) %></td> 
        <td><%= link_to "Jeannie Yim", player_path(30) %></td>
        <td>Duke</td> 
      </tr> 
      <tr>
        <td>14</td> 
        <td><%= link_to "George Chang", player_path(34) %></td> 
        <td><%= link_to "Alissa Montalbano", player_path(45) %></td>
        <td>Duke/Adelphi</td> 
      </tr> 
      <tr>
        <td>15</td> 
        <td><%= link_to "Stephen Kwok", player_path(52) %></td> 
        <td><%= link_to "Amy Zhao", player_path(33) %></td>
        <td>Duke</td> 
      </tr> 
      <tr>
        <td>16</td> 
        <td><%= link_to "Gary Zhang", player_path(51) %></td> 
        <td><%= link_to "Judith Leng", player_path(54) %></td>
        <td>Duke</td> 
      </tr> 
      <tr>
        <td>17</td> 
        <td><%= link_to "Pritak Patel", player_path(31) %></td> 
        <td><%= link_to "April Pun", player_path(61) %></td>
        <td>Duke</td> 
      </tr> 
      <tr>
        <td>18</td> 
        <td><%= link_to "Sameer Dhar", player_path(6) %> </td> 
        <td><%= link_to "Connie Wang", player_path(20) %> </td> 
        <td>WM/JMU</td> 
      </tr> 
      <tr>
        <td>19</td> 
        <td><%= link_to "Rijo Reji", player_path(37) %></td> 
        <td><%= link_to "Sharon Ma", player_path(36) %></td>
        <td>RBC</td> 
      </tr> 
      <tr>
        <td>20</td> 
        <td><%= link_to "Don Lanka ranasinghe", player_path(18) %> </td> 
        <td><%= link_to "Anusha Liyanage", player_path(16) %> </td>
        <td>Virginia Beach</td> 
      </tr> 
    </tbody> 
  </table> 
</div> 

<div class="col-md-8 col-md-offset-2">
  <h2 class="spacer">Wait List</h2>
  <table class="table table-hover spacer"> 
    <thead>
      <tr>
        <th></th>
        <th>Partner 1</th> 
        <th>Partner 2</th> 
        <th>Club</th> 
      </tr> 
    </thead>

    <tbody> 
      <tr>
        <td>1</td> 
        <td><%= link_to "Hannah Nguyen", player_path(25) %></td>
        <td><%= link_to "Min Shao", player_path(27) %></td> 
        <td>GMU Badminton Club</td>
      </tr>
      <tr>
        <td>2</td>
        <td><%= link_to "Desh Ranjan", player_path(23) %></td> 
        <td>Request</td>
        <td>Virginia Beach</td>
      </tr>

      <tr>
        <td>3</td> 
        <td><%= link_to "Kang Hao Chen", player_path(35) %></td>
        <td>Request</td>
        <td>Evergreen</td>
      </tr> 
    </tbody> 
  </table> 
</div>